version: '3.8'
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      POSTGRES_USER: ezdating
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ezdating
    ports:
      - "5432:5432"
    volumes: 
      - ~/Documents/docker/postgres14/data:/var/lib/postgresql/data
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=ezdating
  #     - POSTGRES_PASSWORD=123456
  #     - POSTGRES_DB=ezdating
  #   ports:
  #     - '5432:5432'
  #   volumes: 
  #     - ~/Documents/docker/postgres14/data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - ~/Documents/docker/redis/data:/data
volumes:
  db:
    driver: local
