version: '3.8'
services:
  db:
    container_name: ezd_postgres
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      POSTGRES_USER: ezdating
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ezdating
    ports:
      - "5432:5432"
    volumes: 
      - ~/Documents/docker/ezd_postgres/data:/var/lib/postgresql/data
  redis:
    container_name: ezd_redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes: 
      - ~/Documents/docker/ezd_redis/data:/data
volumes:
  db:
    driver: local
