version: '3.8'
services:
  postgresql:
    container_name: ezd_postgres
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      POSTGRES_USER: ":${POSTGRES_USER}"
      POSTGRES_PASSWORD: ":${POSTGRES_PASS}"
      POSTGRES_DB: ":${POSTGRES_DB_NAME}"
    ports:
      - "5432:5432"
    volumes: 
      - ~/Documents/docker/ezd_postgres/data:/var/lib/postgresql/data
  redis:
    container_name: ezd_redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes: 
      - ~/Documents/docker/ezd_redis/data:/data
volumes:
  postgresql:
    driver: local
  redis:
    driver: local
