export const HttpErrorCodes = {
  CONFLICT_USER: 'CONFLICT_USER',
  CONFLICT_RELATIONSHIP_STATUS: 'CONFLICT_RELATIONSHIP_STATUS',
  CONVERSATION_DOES_NOT_EXIST: 'CONVERSATION_DOES_NOT_EXIST',
  FILE_DOES_NOT_EXIST: 'FILE_DOES_NOT_EXIST',
  RELATIONSHIP_DOES_NOT_EXIST: 'RELATIONSHIP_DOES_NOT_EXIST',
  STATE_DOES_NOT_EXIST: 'STATE_DOES_NOT_EXIST',
  USER_DOES_NOT_EXIST: 'USER_DOES_NOT_EXIST',
  USER_HAS_BEEN_BANNED: 'USER_HAS_BEEN_BANNED',
  USER_RELATIONSHIP_STATUS_DOES_NOT_EXIST:
    'USER_RELATIONSHIP_STATUS_DOES_NOT_EXIST',
};
