export const AppConfig = {
  APP_NAME: 'Research',
  PUBLIC_ENDPOINT_METADATA: 'isPublic',
  REFRESH_TOKEN_EXPIRES: 100,
  ACCESS_TOKEN_EXPIRES: '10m',
  UPLOAD_PHOTOS_LIMIT: 6,
  UPLOAD_PHOTO_MAX_FILE_SIZE: 10 * 1024 * 1024,
  USER_ROLES_KEY: 'roles',
  USER_FILTER_MAX_DISTANCE: 2000000,
};
